/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module lfsr16(clk, rst, q);
  wire [15:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  input clk;
  output [15:0] q;
  input rst;
  sky130_fd_sc_hd__xor2_4 _41_ (
    .A(_28_),
    .B(_30_),
    .X(_21_)
  );
  sky130_fd_sc_hd__xnor2_1 _42_ (
    .A(_26_),
    .B(_27_),
    .Y(_22_)
  );
  sky130_fd_sc_hd__xnor3_1 _43_ (
    .A(_25_),
    .B(_21_),
    .C(_22_),
    .X(_23_)
  );
  sky130_fd_sc_hd__or2_0 _44_ (
    .A(_40_),
    .B(_23_),
    .X(_05_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _45_ (
    .A(_24_),
    .SLEEP(_40_),
    .X(_12_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _46_ (
    .A(_31_),
    .SLEEP(_40_),
    .X(_13_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _47_ (
    .A(_32_),
    .SLEEP(_40_),
    .X(_14_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _48_ (
    .A(_33_),
    .SLEEP(_40_),
    .X(_15_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _49_ (
    .A(_34_),
    .SLEEP(_40_),
    .X(_16_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _50_ (
    .A(_35_),
    .SLEEP(_40_),
    .X(_17_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _51_ (
    .A(_36_),
    .SLEEP(_40_),
    .X(_18_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _52_ (
    .A(_37_),
    .SLEEP(_40_),
    .X(_19_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _53_ (
    .A(_38_),
    .SLEEP(_40_),
    .X(_20_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _54_ (
    .A(_39_),
    .SLEEP(_40_),
    .X(_06_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _55_ (
    .A(_25_),
    .SLEEP(_40_),
    .X(_07_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _56_ (
    .A(_26_),
    .SLEEP(_40_),
    .X(_08_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _57_ (
    .A(_27_),
    .SLEEP(_40_),
    .X(_09_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _58_ (
    .A(_28_),
    .SLEEP(_40_),
    .X(_10_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _59_ (
    .A(_29_),
    .SLEEP(_40_),
    .X(_11_)
  );
  sky130_fd_sc_hd__dfxtp_1 _60_ (
    .CLK(clk),
    .D(_00_[8]),
    .Q(q[8])
  );
  sky130_fd_sc_hd__dfxtp_1 _61_ (
    .CLK(clk),
    .D(_00_[9]),
    .Q(q[9])
  );
  sky130_fd_sc_hd__dfxtp_1 _62_ (
    .CLK(clk),
    .D(_00_[10]),
    .Q(q[10])
  );
  sky130_fd_sc_hd__dfxtp_1 _63_ (
    .CLK(clk),
    .D(_00_[11]),
    .Q(q[11])
  );
  sky130_fd_sc_hd__dfxtp_1 _64_ (
    .CLK(clk),
    .D(_00_[12]),
    .Q(q[12])
  );
  sky130_fd_sc_hd__dfxtp_1 _65_ (
    .CLK(clk),
    .D(_00_[13]),
    .Q(q[13])
  );
  sky130_fd_sc_hd__dfxtp_1 _66_ (
    .CLK(clk),
    .D(_00_[14]),
    .Q(q[14])
  );
  sky130_fd_sc_hd__dfxtp_1 _67_ (
    .CLK(clk),
    .D(_00_[15]),
    .Q(q[15])
  );
  sky130_fd_sc_hd__dfxtp_1 _68_ (
    .CLK(clk),
    .D(_00_[0]),
    .Q(q[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _69_ (
    .CLK(clk),
    .D(_00_[1]),
    .Q(q[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _70_ (
    .CLK(clk),
    .D(_00_[2]),
    .Q(q[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _71_ (
    .CLK(clk),
    .D(_00_[3]),
    .Q(q[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _72_ (
    .CLK(clk),
    .D(_00_[4]),
    .Q(q[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _73_ (
    .CLK(clk),
    .D(_00_[5]),
    .Q(q[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _74_ (
    .CLK(clk),
    .D(_00_[6]),
    .Q(q[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _75_ (
    .CLK(clk),
    .D(_00_[7]),
    .Q(q[7])
  );
  assign _26_ = q[11];
  assign _27_ = q[12];
  assign _25_ = q[10];
  assign _40_ = rst;
  assign _00_[0] = _05_;
  assign _24_ = q[0];
  assign _00_[1] = _12_;
  assign _31_ = q[1];
  assign _00_[2] = _13_;
  assign _32_ = q[2];
  assign _00_[3] = _14_;
  assign _33_ = q[3];
  assign _00_[4] = _15_;
  assign _34_ = q[4];
  assign _00_[5] = _16_;
  assign _35_ = q[5];
  assign _00_[6] = _17_;
  assign _36_ = q[6];
  assign _00_[7] = _18_;
  assign _37_ = q[7];
  assign _00_[8] = _19_;
  assign _38_ = q[8];
  assign _00_[9] = _20_;
  assign _39_ = q[9];
  assign _00_[10] = _06_;
  assign _00_[11] = _07_;
  assign _00_[12] = _08_;
  assign _00_[13] = _09_;
  assign _28_ = q[13];
  assign _00_[14] = _10_;
  assign _29_ = q[14];
  assign _00_[15] = _11_;
  assign _30_ = q[15];
endmodule
