/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module adder32(a, b, cin, s, cout);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _370_;
  wire _371_;
  wire _372_;
  wire _373_;
  wire _374_;
  wire _375_;
  wire _376_;
  wire _377_;
  wire _378_;
  wire _379_;
  wire _380_;
  wire _381_;
  wire _382_;
  wire _383_;
  wire _384_;
  wire _385_;
  wire _386_;
  wire _387_;
  wire _388_;
  wire _389_;
  wire _390_;
  wire _391_;
  wire _392_;
  wire _393_;
  wire _394_;
  wire _395_;
  wire _396_;
  wire _397_;
  wire _398_;
  wire _399_;
  wire _400_;
  wire _401_;
  wire _402_;
  wire _403_;
  wire _404_;
  wire _405_;
  wire _406_;
  wire _407_;
  wire _408_;
  wire _409_;
  wire _410_;
  wire _411_;
  wire _412_;
  input [31:0] a;
  input [31:0] b;
  input cin;
  output cout;
  output [31:0] s;
  sky130_fd_sc_hd__xor2_1 _413_ (
    .A(_191_),
    .B(_223_),
    .X(_380_)
  );
  sky130_fd_sc_hd__xnor2_1 _414_ (
    .A(_189_),
    .B(_221_),
    .Y(_254_)
  );
  sky130_fd_sc_hd__nor2_1 _415_ (
    .A(_219_),
    .B(_251_),
    .Y(_255_)
  );
  sky130_fd_sc_hd__or2_2 _416_ (
    .A(_218_),
    .B(_250_),
    .X(_256_)
  );
  sky130_fd_sc_hd__or2_2 _417_ (
    .A(_217_),
    .B(_249_),
    .X(_257_)
  );
  sky130_fd_sc_hd__xnor2_1 _418_ (
    .A(_216_),
    .B(_248_),
    .Y(_258_)
  );
  sky130_fd_sc_hd__nor2_1 _419_ (
    .A(_215_),
    .B(_247_),
    .Y(_259_)
  );
  sky130_fd_sc_hd__maj3_2 _420_ (
    .A(_188_),
    .B(_220_),
    .C(_252_),
    .X(_260_)
  );
  sky130_fd_sc_hd__maj3_2 _421_ (
    .A(_199_),
    .B(_231_),
    .C(_260_),
    .X(_261_)
  );
  sky130_fd_sc_hd__maj3_2 _422_ (
    .A(_210_),
    .B(_242_),
    .C(_261_),
    .X(_262_)
  );
  sky130_fd_sc_hd__maj3_2 _423_ (
    .A(_213_),
    .B(_245_),
    .C(_262_),
    .X(_263_)
  );
  sky130_fd_sc_hd__lpflow_inputiso0n_1 _424_ (
    .A(_214_),
    .SLEEP_B(_246_),
    .X(_264_)
  );
  sky130_fd_sc_hd__nor2_1 _425_ (
    .A(_214_),
    .B(_246_),
    .Y(_265_)
  );
  sky130_fd_sc_hd__nor2_1 _426_ (
    .A(_264_),
    .B(_265_),
    .Y(_266_)
  );
  sky130_fd_sc_hd__and2_0 _427_ (
    .A(_215_),
    .B(_247_),
    .X(_267_)
  );
  sky130_fd_sc_hd__a211oi_2 _428_ (
    .A1(_263_),
    .A2(_266_),
    .B1(_267_),
    .C1(_264_),
    .Y(_268_)
  );
  sky130_fd_sc_hd__nand2_1 _429_ (
    .A(_216_),
    .B(_248_),
    .Y(_269_)
  );
  sky130_fd_sc_hd__nand2_1 _430_ (
    .A(_217_),
    .B(_249_),
    .Y(_270_)
  );
  sky130_fd_sc_hd__o311ai_1 _431_ (
    .A1(_258_),
    .A2(_259_),
    .A3(_268_),
    .B1(_269_),
    .C1(_270_),
    .Y(_271_)
  );
  sky130_fd_sc_hd__and2_0 _432_ (
    .A(_218_),
    .B(_250_),
    .X(_272_)
  );
  sky130_fd_sc_hd__and2_0 _433_ (
    .A(_219_),
    .B(_251_),
    .X(_273_)
  );
  sky130_fd_sc_hd__a311oi_2 _434_ (
    .A1(_256_),
    .A2(_257_),
    .A3(_271_),
    .B1(_272_),
    .C1(_273_),
    .Y(_274_)
  );
  sky130_fd_sc_hd__or2_2 _435_ (
    .A(_190_),
    .B(_222_),
    .X(_275_)
  );
  sky130_fd_sc_hd__nand2_1 _436_ (
    .A(_190_),
    .B(_222_),
    .Y(_276_)
  );
  sky130_fd_sc_hd__nand2_1 _437_ (
    .A(_275_),
    .B(_276_),
    .Y(_277_)
  );
  sky130_fd_sc_hd__nand2_1 _438_ (
    .A(_189_),
    .B(_221_),
    .Y(_278_)
  );
  sky130_fd_sc_hd__nand2_1 _439_ (
    .A(_278_),
    .B(_276_),
    .Y(_279_)
  );
  sky130_fd_sc_hd__nand2_1 _440_ (
    .A(_275_),
    .B(_279_),
    .Y(_280_)
  );
  sky130_fd_sc_hd__o41ai_2 _441_ (
    .A1(_254_),
    .A2(_255_),
    .A3(_274_),
    .A4(_277_),
    .B1(_280_),
    .Y(_281_)
  );
  sky130_fd_sc_hd__xor2_1 _442_ (
    .A(_380_),
    .B(_281_),
    .X(_384_)
  );
  sky130_fd_sc_hd__nand2_1 _443_ (
    .A(_191_),
    .B(_223_),
    .Y(_282_)
  );
  sky130_fd_sc_hd__nand2_1 _444_ (
    .A(_380_),
    .B(_281_),
    .Y(_283_)
  );
  sky130_fd_sc_hd__nand2_1 _445_ (
    .A(_282_),
    .B(_283_),
    .Y(_284_)
  );
  sky130_fd_sc_hd__nand2_1 _446_ (
    .A(_192_),
    .B(_224_),
    .Y(_285_)
  );
  sky130_fd_sc_hd__nor2_1 _447_ (
    .A(_192_),
    .B(_224_),
    .Y(_286_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _448_ (
    .A(_285_),
    .SLEEP(_286_),
    .X(_287_)
  );
  sky130_fd_sc_hd__xor2_1 _449_ (
    .A(_284_),
    .B(_287_),
    .X(_385_)
  );
  sky130_fd_sc_hd__xnor2_1 _450_ (
    .A(_193_),
    .B(_225_),
    .Y(_288_)
  );
  sky130_fd_sc_hd__o21ai_0 _451_ (
    .A1(_282_),
    .A2(_286_),
    .B1(_285_),
    .Y(_289_)
  );
  sky130_fd_sc_hd__a31oi_2 _452_ (
    .A1(_380_),
    .A2(_281_),
    .A3(_287_),
    .B1(_289_),
    .Y(_290_)
  );
  sky130_fd_sc_hd__xor2_1 _453_ (
    .A(_288_),
    .B(_290_),
    .X(_386_)
  );
  sky130_fd_sc_hd__nand2_1 _454_ (
    .A(_193_),
    .B(_225_),
    .Y(_291_)
  );
  sky130_fd_sc_hd__o21ai_1 _455_ (
    .A1(_288_),
    .A2(_290_),
    .B1(_291_),
    .Y(_292_)
  );
  sky130_fd_sc_hd__or2_2 _456_ (
    .A(_194_),
    .B(_226_),
    .X(_293_)
  );
  sky130_fd_sc_hd__nand2_1 _457_ (
    .A(_194_),
    .B(_226_),
    .Y(_294_)
  );
  sky130_fd_sc_hd__nand2_1 _458_ (
    .A(_293_),
    .B(_294_),
    .Y(_295_)
  );
  sky130_fd_sc_hd__xnor2_1 _459_ (
    .A(_292_),
    .B(_295_),
    .Y(_387_)
  );
  sky130_fd_sc_hd__nor2_1 _460_ (
    .A(_195_),
    .B(_227_),
    .Y(_296_)
  );
  sky130_fd_sc_hd__nand2_1 _461_ (
    .A(_195_),
    .B(_227_),
    .Y(_297_)
  );
  sky130_fd_sc_hd__nor2b_1 _462_ (
    .A(_296_),
    .B_N(_297_),
    .Y(_298_)
  );
  sky130_fd_sc_hd__o211ai_2 _463_ (
    .A1(_288_),
    .A2(_290_),
    .B1(_294_),
    .C1(_291_),
    .Y(_299_)
  );
  sky130_fd_sc_hd__nand2_1 _464_ (
    .A(_293_),
    .B(_299_),
    .Y(_300_)
  );
  sky130_fd_sc_hd__xnor2_1 _465_ (
    .A(_298_),
    .B(_300_),
    .Y(_388_)
  );
  sky130_fd_sc_hd__o21ai_1 _466_ (
    .A1(_296_),
    .A2(_300_),
    .B1(_297_),
    .Y(_301_)
  );
  sky130_fd_sc_hd__nand2_1 _467_ (
    .A(_196_),
    .B(_228_),
    .Y(_302_)
  );
  sky130_fd_sc_hd__nor2_1 _468_ (
    .A(_196_),
    .B(_228_),
    .Y(_303_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _469_ (
    .A(_302_),
    .SLEEP(_303_),
    .X(_304_)
  );
  sky130_fd_sc_hd__xor2_1 _470_ (
    .A(_301_),
    .B(_304_),
    .X(_389_)
  );
  sky130_fd_sc_hd__xnor2_1 _471_ (
    .A(_197_),
    .B(_229_),
    .Y(_305_)
  );
  sky130_fd_sc_hd__a21oi_1 _472_ (
    .A1(_297_),
    .A2(_302_),
    .B1(_303_),
    .Y(_306_)
  );
  sky130_fd_sc_hd__a41oi_2 _473_ (
    .A1(_293_),
    .A2(_298_),
    .A3(_299_),
    .A4(_304_),
    .B1(_306_),
    .Y(_307_)
  );
  sky130_fd_sc_hd__xor2_1 _474_ (
    .A(_305_),
    .B(_307_),
    .X(_390_)
  );
  sky130_fd_sc_hd__nand2_1 _475_ (
    .A(_197_),
    .B(_229_),
    .Y(_308_)
  );
  sky130_fd_sc_hd__o21ai_1 _476_ (
    .A1(_305_),
    .A2(_307_),
    .B1(_308_),
    .Y(_309_)
  );
  sky130_fd_sc_hd__xnor2_1 _477_ (
    .A(_198_),
    .B(_230_),
    .Y(_310_)
  );
  sky130_fd_sc_hd__xnor2_1 _478_ (
    .A(_309_),
    .B(_310_),
    .Y(_391_)
  );
  sky130_fd_sc_hd__xor2_1 _479_ (
    .A(_200_),
    .B(_232_),
    .X(_311_)
  );
  sky130_fd_sc_hd__nor2_1 _480_ (
    .A(_198_),
    .B(_230_),
    .Y(_312_)
  );
  sky130_fd_sc_hd__nand2_1 _481_ (
    .A(_198_),
    .B(_230_),
    .Y(_313_)
  );
  sky130_fd_sc_hd__o21a_1 _482_ (
    .A1(_308_),
    .A2(_312_),
    .B1(_313_),
    .X(_314_)
  );
  sky130_fd_sc_hd__o31ai_2 _483_ (
    .A1(_305_),
    .A2(_307_),
    .A3(_310_),
    .B1(_314_),
    .Y(_315_)
  );
  sky130_fd_sc_hd__xor2_1 _484_ (
    .A(_311_),
    .B(_315_),
    .X(_393_)
  );
  sky130_fd_sc_hd__maj3_1 _485_ (
    .A(_200_),
    .B(_232_),
    .C(_315_),
    .X(_316_)
  );
  sky130_fd_sc_hd__nand2_1 _486_ (
    .A(_201_),
    .B(_233_),
    .Y(_317_)
  );
  sky130_fd_sc_hd__nor2_1 _487_ (
    .A(_201_),
    .B(_233_),
    .Y(_318_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _488_ (
    .A(_317_),
    .SLEEP(_318_),
    .X(_319_)
  );
  sky130_fd_sc_hd__xor2_1 _489_ (
    .A(_316_),
    .B(_319_),
    .X(_394_)
  );
  sky130_fd_sc_hd__xnor2_1 _490_ (
    .A(_202_),
    .B(_234_),
    .Y(_320_)
  );
  sky130_fd_sc_hd__nand2_1 _491_ (
    .A(_200_),
    .B(_232_),
    .Y(_321_)
  );
  sky130_fd_sc_hd__o21ai_0 _492_ (
    .A1(_321_),
    .A2(_318_),
    .B1(_317_),
    .Y(_322_)
  );
  sky130_fd_sc_hd__a31oi_2 _493_ (
    .A1(_311_),
    .A2(_315_),
    .A3(_319_),
    .B1(_322_),
    .Y(_323_)
  );
  sky130_fd_sc_hd__xor2_1 _494_ (
    .A(_320_),
    .B(_323_),
    .X(_395_)
  );
  sky130_fd_sc_hd__nand2_1 _495_ (
    .A(_202_),
    .B(_234_),
    .Y(_324_)
  );
  sky130_fd_sc_hd__o21ai_1 _496_ (
    .A1(_320_),
    .A2(_323_),
    .B1(_324_),
    .Y(_325_)
  );
  sky130_fd_sc_hd__nand2_1 _497_ (
    .A(_203_),
    .B(_235_),
    .Y(_326_)
  );
  sky130_fd_sc_hd__or2_2 _498_ (
    .A(_203_),
    .B(_235_),
    .X(_327_)
  );
  sky130_fd_sc_hd__nand2_1 _499_ (
    .A(_326_),
    .B(_327_),
    .Y(_328_)
  );
  sky130_fd_sc_hd__xnor2_1 _500_ (
    .A(_325_),
    .B(_328_),
    .Y(_396_)
  );
  sky130_fd_sc_hd__and2_0 _501_ (
    .A(_204_),
    .B(_236_),
    .X(_329_)
  );
  sky130_fd_sc_hd__nor2_1 _502_ (
    .A(_204_),
    .B(_236_),
    .Y(_330_)
  );
  sky130_fd_sc_hd__nor2_1 _503_ (
    .A(_329_),
    .B(_330_),
    .Y(_331_)
  );
  sky130_fd_sc_hd__nand2_1 _504_ (
    .A(_324_),
    .B(_326_),
    .Y(_332_)
  );
  sky130_fd_sc_hd__nand2_1 _505_ (
    .A(_327_),
    .B(_332_),
    .Y(_333_)
  );
  sky130_fd_sc_hd__o31ai_2 _506_ (
    .A1(_320_),
    .A2(_323_),
    .A3(_328_),
    .B1(_333_),
    .Y(_334_)
  );
  sky130_fd_sc_hd__xor2_1 _507_ (
    .A(_331_),
    .B(_334_),
    .X(_397_)
  );
  sky130_fd_sc_hd__a21o_1 _508_ (
    .A1(_331_),
    .A2(_334_),
    .B1(_329_),
    .X(_335_)
  );
  sky130_fd_sc_hd__xnor2_1 _509_ (
    .A(_205_),
    .B(_237_),
    .Y(_336_)
  );
  sky130_fd_sc_hd__xnor2_1 _510_ (
    .A(_335_),
    .B(_336_),
    .Y(_398_)
  );
  sky130_fd_sc_hd__nor2_1 _511_ (
    .A(_205_),
    .B(_237_),
    .Y(_337_)
  );
  sky130_fd_sc_hd__xnor2_1 _512_ (
    .A(_206_),
    .B(_238_),
    .Y(_338_)
  );
  sky130_fd_sc_hd__a221oi_2 _513_ (
    .A1(_205_),
    .A2(_237_),
    .B1(_331_),
    .B2(_334_),
    .C1(_329_),
    .Y(_339_)
  );
  sky130_fd_sc_hd__nor3_1 _514_ (
    .A(_337_),
    .B(_338_),
    .C(_339_),
    .Y(_340_)
  );
  sky130_fd_sc_hd__o21ai_0 _515_ (
    .A1(_337_),
    .A2(_339_),
    .B1(_338_),
    .Y(_341_)
  );
  sky130_fd_sc_hd__nor2b_1 _516_ (
    .A(_340_),
    .B_N(_341_),
    .Y(_399_)
  );
  sky130_fd_sc_hd__nand2_1 _517_ (
    .A(_206_),
    .B(_238_),
    .Y(_342_)
  );
  sky130_fd_sc_hd__o31ai_1 _518_ (
    .A1(_337_),
    .A2(_338_),
    .A3(_339_),
    .B1(_342_),
    .Y(_343_)
  );
  sky130_fd_sc_hd__or2_2 _519_ (
    .A(_207_),
    .B(_239_),
    .X(_344_)
  );
  sky130_fd_sc_hd__nand2_1 _520_ (
    .A(_207_),
    .B(_239_),
    .Y(_345_)
  );
  sky130_fd_sc_hd__nand2_1 _521_ (
    .A(_344_),
    .B(_345_),
    .Y(_346_)
  );
  sky130_fd_sc_hd__xnor2_1 _522_ (
    .A(_343_),
    .B(_346_),
    .Y(_400_)
  );
  sky130_fd_sc_hd__nor2_1 _523_ (
    .A(_208_),
    .B(_240_),
    .Y(_347_)
  );
  sky130_fd_sc_hd__lpflow_inputiso0n_1 _524_ (
    .A(_208_),
    .SLEEP_B(_240_),
    .X(_348_)
  );
  sky130_fd_sc_hd__nor2_1 _525_ (
    .A(_347_),
    .B(_348_),
    .Y(_349_)
  );
  sky130_fd_sc_hd__o311ai_1 _526_ (
    .A1(_337_),
    .A2(_338_),
    .A3(_339_),
    .B1(_345_),
    .C1(_342_),
    .Y(_350_)
  );
  sky130_fd_sc_hd__and3_1 _527_ (
    .A(_344_),
    .B(_349_),
    .C(_350_),
    .X(_351_)
  );
  sky130_fd_sc_hd__a21oi_1 _528_ (
    .A1(_344_),
    .A2(_350_),
    .B1(_349_),
    .Y(_352_)
  );
  sky130_fd_sc_hd__nor2_1 _529_ (
    .A(_351_),
    .B(_352_),
    .Y(_401_)
  );
  sky130_fd_sc_hd__nor2_1 _530_ (
    .A(_348_),
    .B(_351_),
    .Y(_353_)
  );
  sky130_fd_sc_hd__nor2_1 _531_ (
    .A(_209_),
    .B(_241_),
    .Y(_354_)
  );
  sky130_fd_sc_hd__and2_0 _532_ (
    .A(_209_),
    .B(_241_),
    .X(_355_)
  );
  sky130_fd_sc_hd__nor2_1 _533_ (
    .A(_354_),
    .B(_355_),
    .Y(_356_)
  );
  sky130_fd_sc_hd__xnor2_1 _534_ (
    .A(_353_),
    .B(_356_),
    .Y(_402_)
  );
  sky130_fd_sc_hd__xnor2_1 _535_ (
    .A(_211_),
    .B(_243_),
    .Y(_357_)
  );
  sky130_fd_sc_hd__a311oi_2 _536_ (
    .A1(_344_),
    .A2(_349_),
    .A3(_350_),
    .B1(_355_),
    .C1(_348_),
    .Y(_358_)
  );
  sky130_fd_sc_hd__nor3_1 _537_ (
    .A(_354_),
    .B(_357_),
    .C(_358_),
    .Y(_359_)
  );
  sky130_fd_sc_hd__o21a_1 _538_ (
    .A1(_354_),
    .A2(_358_),
    .B1(_357_),
    .X(_360_)
  );
  sky130_fd_sc_hd__nor2_1 _539_ (
    .A(_359_),
    .B(_360_),
    .Y(_404_)
  );
  sky130_fd_sc_hd__nand2_1 _540_ (
    .A(_211_),
    .B(_243_),
    .Y(_361_)
  );
  sky130_fd_sc_hd__o31ai_1 _541_ (
    .A1(_354_),
    .A2(_357_),
    .A3(_358_),
    .B1(_361_),
    .Y(_362_)
  );
  sky130_fd_sc_hd__xnor2_1 _542_ (
    .A(_212_),
    .B(_244_),
    .Y(_363_)
  );
  sky130_fd_sc_hd__xnor2_1 _543_ (
    .A(_362_),
    .B(_363_),
    .Y(_405_)
  );
  sky130_fd_sc_hd__maj3_1 _544_ (
    .A(_212_),
    .B(_244_),
    .C(_362_),
    .X(_253_)
  );
  sky130_fd_sc_hd__xnor2_1 _545_ (
    .A(_188_),
    .B(_220_),
    .Y(_364_)
  );
  sky130_fd_sc_hd__xnor2_1 _546_ (
    .A(_252_),
    .B(_364_),
    .Y(_381_)
  );
  sky130_fd_sc_hd__xnor2_1 _547_ (
    .A(_199_),
    .B(_231_),
    .Y(_365_)
  );
  sky130_fd_sc_hd__xnor2_1 _548_ (
    .A(_260_),
    .B(_365_),
    .Y(_392_)
  );
  sky130_fd_sc_hd__xnor2_1 _549_ (
    .A(_210_),
    .B(_242_),
    .Y(_366_)
  );
  sky130_fd_sc_hd__xnor2_1 _550_ (
    .A(_261_),
    .B(_366_),
    .Y(_403_)
  );
  sky130_fd_sc_hd__xnor2_1 _551_ (
    .A(_213_),
    .B(_245_),
    .Y(_367_)
  );
  sky130_fd_sc_hd__xnor2_1 _552_ (
    .A(_262_),
    .B(_367_),
    .Y(_406_)
  );
  sky130_fd_sc_hd__xor2_1 _553_ (
    .A(_263_),
    .B(_266_),
    .X(_407_)
  );
  sky130_fd_sc_hd__a21oi_1 _554_ (
    .A1(_263_),
    .A2(_266_),
    .B1(_264_),
    .Y(_368_)
  );
  sky130_fd_sc_hd__or2_2 _555_ (
    .A(_267_),
    .B(_259_),
    .X(_369_)
  );
  sky130_fd_sc_hd__xor2_1 _556_ (
    .A(_368_),
    .B(_369_),
    .X(_408_)
  );
  sky130_fd_sc_hd__nor2_1 _557_ (
    .A(_259_),
    .B(_268_),
    .Y(_370_)
  );
  sky130_fd_sc_hd__xnor2_1 _558_ (
    .A(_258_),
    .B(_370_),
    .Y(_409_)
  );
  sky130_fd_sc_hd__o31ai_1 _559_ (
    .A1(_258_),
    .A2(_259_),
    .A3(_268_),
    .B1(_269_),
    .Y(_371_)
  );
  sky130_fd_sc_hd__nand2_1 _560_ (
    .A(_270_),
    .B(_257_),
    .Y(_372_)
  );
  sky130_fd_sc_hd__xnor2_1 _561_ (
    .A(_371_),
    .B(_372_),
    .Y(_410_)
  );
  sky130_fd_sc_hd__nand2b_1 _562_ (
    .A_N(_272_),
    .B(_256_),
    .Y(_373_)
  );
  sky130_fd_sc_hd__and2_1 _563_ (
    .A(_257_),
    .B(_271_),
    .X(_374_)
  );
  sky130_fd_sc_hd__xnor2_1 _564_ (
    .A(_373_),
    .B(_374_),
    .Y(_411_)
  );
  sky130_fd_sc_hd__a21oi_1 _565_ (
    .A1(_256_),
    .A2(_374_),
    .B1(_272_),
    .Y(_375_)
  );
  sky130_fd_sc_hd__nor2_1 _566_ (
    .A(_273_),
    .B(_255_),
    .Y(_376_)
  );
  sky130_fd_sc_hd__xnor2_1 _567_ (
    .A(_375_),
    .B(_376_),
    .Y(_412_)
  );
  sky130_fd_sc_hd__nor3_1 _568_ (
    .A(_254_),
    .B(_255_),
    .C(_274_),
    .Y(_377_)
  );
  sky130_fd_sc_hd__o21a_1 _569_ (
    .A1(_255_),
    .A2(_274_),
    .B1(_254_),
    .X(_378_)
  );
  sky130_fd_sc_hd__nor2_1 _570_ (
    .A(_377_),
    .B(_378_),
    .Y(_382_)
  );
  sky130_fd_sc_hd__a21oi_1 _571_ (
    .A1(_189_),
    .A2(_221_),
    .B1(_377_),
    .Y(_379_)
  );
  sky130_fd_sc_hd__xor2_1 _572_ (
    .A(_277_),
    .B(_379_),
    .X(_383_)
  );
  assign _191_ = a[12];
  assign _223_ = b[12];
  assign _190_ = a[11];
  assign _222_ = b[11];
  assign _189_ = a[10];
  assign _221_ = b[10];
  assign _219_ = a[9];
  assign _251_ = b[9];
  assign _218_ = a[8];
  assign _250_ = b[8];
  assign _217_ = a[7];
  assign _249_ = b[7];
  assign _216_ = a[6];
  assign _248_ = b[6];
  assign _215_ = a[5];
  assign _247_ = b[5];
  assign _214_ = a[4];
  assign _246_ = b[4];
  assign _213_ = a[3];
  assign _245_ = b[3];
  assign _210_ = a[2];
  assign _242_ = b[2];
  assign _199_ = a[1];
  assign _231_ = b[1];
  assign _188_ = a[0];
  assign _220_ = b[0];
  assign _252_ = cin;
  assign s[12] = _384_;
  assign _192_ = a[13];
  assign _224_ = b[13];
  assign s[13] = _385_;
  assign _193_ = a[14];
  assign _225_ = b[14];
  assign s[14] = _386_;
  assign _194_ = a[15];
  assign _226_ = b[15];
  assign s[15] = _387_;
  assign _195_ = a[16];
  assign _227_ = b[16];
  assign s[16] = _388_;
  assign _196_ = a[17];
  assign _228_ = b[17];
  assign s[17] = _389_;
  assign _197_ = a[18];
  assign _229_ = b[18];
  assign s[18] = _390_;
  assign _198_ = a[19];
  assign _230_ = b[19];
  assign s[19] = _391_;
  assign _200_ = a[20];
  assign _232_ = b[20];
  assign s[20] = _393_;
  assign _201_ = a[21];
  assign _233_ = b[21];
  assign s[21] = _394_;
  assign _202_ = a[22];
  assign _234_ = b[22];
  assign s[22] = _395_;
  assign _203_ = a[23];
  assign _235_ = b[23];
  assign s[23] = _396_;
  assign _204_ = a[24];
  assign _236_ = b[24];
  assign s[24] = _397_;
  assign _205_ = a[25];
  assign _237_ = b[25];
  assign s[25] = _398_;
  assign _206_ = a[26];
  assign _238_ = b[26];
  assign s[26] = _399_;
  assign _207_ = a[27];
  assign _239_ = b[27];
  assign s[27] = _400_;
  assign _208_ = a[28];
  assign _240_ = b[28];
  assign s[28] = _401_;
  assign _209_ = a[29];
  assign _241_ = b[29];
  assign s[29] = _402_;
  assign _211_ = a[30];
  assign _243_ = b[30];
  assign s[30] = _404_;
  assign _212_ = a[31];
  assign _244_ = b[31];
  assign s[31] = _405_;
  assign cout = _253_;
  assign s[0] = _381_;
  assign s[1] = _392_;
  assign s[2] = _403_;
  assign s[3] = _406_;
  assign s[4] = _407_;
  assign s[5] = _408_;
  assign s[6] = _409_;
  assign s[7] = _410_;
  assign s[8] = _411_;
  assign s[9] = _412_;
  assign s[10] = _382_;
  assign s[11] = _383_;
endmodule
