/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module adder16(a, b, cin, s, cout);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  input [15:0] a;
  input [15:0] b;
  input cin;
  output cout;
  output [15:0] s;
  sky130_fd_sc_hd__xnor2_1 _190_ (
    .A(_088_),
    .B(_104_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__nor2_1 _191_ (
    .A(_087_),
    .B(_103_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__lpflow_inputiso0n_1 _192_ (
    .A(_086_),
    .SLEEP_B(_102_),
    .X(_134_)
  );
  sky130_fd_sc_hd__nor2_1 _193_ (
    .A(_086_),
    .B(_102_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__nor2_1 _194_ (
    .A(_134_),
    .B(_135_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__or2_2 _195_ (
    .A(_085_),
    .B(_101_),
    .X(_137_)
  );
  sky130_fd_sc_hd__xnor2_1 _196_ (
    .A(_084_),
    .B(_100_),
    .Y(_138_)
  );
  sky130_fd_sc_hd__nor2_1 _197_ (
    .A(_098_),
    .B(_114_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__and2_0 _198_ (
    .A(_097_),
    .B(_113_),
    .X(_140_)
  );
  sky130_fd_sc_hd__nor2_1 _199_ (
    .A(_097_),
    .B(_113_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__nor2_1 _200_ (
    .A(_140_),
    .B(_141_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__or2_2 _201_ (
    .A(_096_),
    .B(_112_),
    .X(_143_)
  );
  sky130_fd_sc_hd__xnor2_1 _202_ (
    .A(_095_),
    .B(_111_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__nor2_1 _203_ (
    .A(_094_),
    .B(_110_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__maj3_2 _204_ (
    .A(_083_),
    .B(_099_),
    .C(_115_),
    .X(_146_)
  );
  sky130_fd_sc_hd__maj3_2 _205_ (
    .A(_090_),
    .B(_106_),
    .C(_146_),
    .X(_147_)
  );
  sky130_fd_sc_hd__maj3_2 _206_ (
    .A(_091_),
    .B(_107_),
    .C(_147_),
    .X(_148_)
  );
  sky130_fd_sc_hd__maj3_2 _207_ (
    .A(_092_),
    .B(_108_),
    .C(_148_),
    .X(_149_)
  );
  sky130_fd_sc_hd__and2_0 _208_ (
    .A(_093_),
    .B(_109_),
    .X(_150_)
  );
  sky130_fd_sc_hd__nor2_1 _209_ (
    .A(_093_),
    .B(_109_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__nor2_1 _210_ (
    .A(_150_),
    .B(_151_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__and2_0 _211_ (
    .A(_094_),
    .B(_110_),
    .X(_153_)
  );
  sky130_fd_sc_hd__a211oi_2 _212_ (
    .A1(_149_),
    .A2(_152_),
    .B1(_153_),
    .C1(_150_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__nand2_1 _213_ (
    .A(_095_),
    .B(_111_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__nand2_1 _214_ (
    .A(_096_),
    .B(_112_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__o311ai_1 _215_ (
    .A1(_144_),
    .A2(_145_),
    .A3(_154_),
    .B1(_155_),
    .C1(_156_),
    .Y(_157_)
  );
  sky130_fd_sc_hd__and2_0 _216_ (
    .A(_098_),
    .B(_114_),
    .X(_158_)
  );
  sky130_fd_sc_hd__a311oi_2 _217_ (
    .A1(_142_),
    .A2(_143_),
    .A3(_157_),
    .B1(_140_),
    .C1(_158_),
    .Y(_159_)
  );
  sky130_fd_sc_hd__nand2_1 _218_ (
    .A(_084_),
    .B(_100_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__nand2_1 _219_ (
    .A(_085_),
    .B(_101_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__o311ai_1 _220_ (
    .A1(_138_),
    .A2(_139_),
    .A3(_159_),
    .B1(_160_),
    .C1(_161_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__and2_0 _221_ (
    .A(_087_),
    .B(_103_),
    .X(_163_)
  );
  sky130_fd_sc_hd__a311oi_2 _222_ (
    .A1(_136_),
    .A2(_137_),
    .A3(_162_),
    .B1(_134_),
    .C1(_163_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__nand2_1 _223_ (
    .A(_088_),
    .B(_104_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__o31ai_1 _224_ (
    .A1(_132_),
    .A2(_133_),
    .A3(_164_),
    .B1(_165_),
    .Y(_166_)
  );
  sky130_fd_sc_hd__maj3_1 _225_ (
    .A(_089_),
    .B(_105_),
    .C(_166_),
    .X(_116_)
  );
  sky130_fd_sc_hd__xnor2_1 _226_ (
    .A(_083_),
    .B(_099_),
    .Y(_167_)
  );
  sky130_fd_sc_hd__xnor2_1 _227_ (
    .A(_115_),
    .B(_167_),
    .Y(_174_)
  );
  sky130_fd_sc_hd__xnor2_1 _228_ (
    .A(_090_),
    .B(_106_),
    .Y(_168_)
  );
  sky130_fd_sc_hd__xnor2_1 _229_ (
    .A(_146_),
    .B(_168_),
    .Y(_181_)
  );
  sky130_fd_sc_hd__xnor2_1 _230_ (
    .A(_091_),
    .B(_107_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__xnor2_1 _231_ (
    .A(_147_),
    .B(_169_),
    .Y(_182_)
  );
  sky130_fd_sc_hd__xnor2_1 _232_ (
    .A(_092_),
    .B(_108_),
    .Y(_170_)
  );
  sky130_fd_sc_hd__xnor2_1 _233_ (
    .A(_148_),
    .B(_170_),
    .Y(_183_)
  );
  sky130_fd_sc_hd__xor2_1 _234_ (
    .A(_149_),
    .B(_152_),
    .X(_184_)
  );
  sky130_fd_sc_hd__a21oi_1 _235_ (
    .A1(_149_),
    .A2(_152_),
    .B1(_150_),
    .Y(_171_)
  );
  sky130_fd_sc_hd__or2_2 _236_ (
    .A(_153_),
    .B(_145_),
    .X(_172_)
  );
  sky130_fd_sc_hd__xor2_1 _237_ (
    .A(_171_),
    .B(_172_),
    .X(_185_)
  );
  sky130_fd_sc_hd__nor2_1 _238_ (
    .A(_145_),
    .B(_154_),
    .Y(_173_)
  );
  sky130_fd_sc_hd__xnor2_1 _239_ (
    .A(_144_),
    .B(_173_),
    .Y(_186_)
  );
  sky130_fd_sc_hd__o31ai_1 _240_ (
    .A1(_144_),
    .A2(_145_),
    .A3(_154_),
    .B1(_155_),
    .Y(_117_)
  );
  sky130_fd_sc_hd__nand2_1 _241_ (
    .A(_156_),
    .B(_143_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__xnor2_1 _242_ (
    .A(_117_),
    .B(_118_),
    .Y(_187_)
  );
  sky130_fd_sc_hd__nand2_1 _243_ (
    .A(_143_),
    .B(_157_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__xnor2_1 _244_ (
    .A(_142_),
    .B(_119_),
    .Y(_188_)
  );
  sky130_fd_sc_hd__a31oi_1 _245_ (
    .A1(_142_),
    .A2(_143_),
    .A3(_157_),
    .B1(_140_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__nor2_1 _246_ (
    .A(_158_),
    .B(_139_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__xnor2_1 _247_ (
    .A(_120_),
    .B(_121_),
    .Y(_189_)
  );
  sky130_fd_sc_hd__nor2_1 _248_ (
    .A(_139_),
    .B(_159_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__xnor2_1 _249_ (
    .A(_138_),
    .B(_122_),
    .Y(_175_)
  );
  sky130_fd_sc_hd__o31ai_1 _250_ (
    .A1(_138_),
    .A2(_139_),
    .A3(_159_),
    .B1(_160_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__nand2_1 _251_ (
    .A(_161_),
    .B(_137_),
    .Y(_124_)
  );
  sky130_fd_sc_hd__xnor2_1 _252_ (
    .A(_123_),
    .B(_124_),
    .Y(_176_)
  );
  sky130_fd_sc_hd__and3_1 _253_ (
    .A(_136_),
    .B(_137_),
    .C(_162_),
    .X(_125_)
  );
  sky130_fd_sc_hd__a21oi_1 _254_ (
    .A1(_137_),
    .A2(_162_),
    .B1(_136_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__nor2_1 _255_ (
    .A(_125_),
    .B(_126_),
    .Y(_177_)
  );
  sky130_fd_sc_hd__nor2_1 _256_ (
    .A(_134_),
    .B(_125_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__nor2_1 _257_ (
    .A(_163_),
    .B(_133_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__xnor2_1 _258_ (
    .A(_127_),
    .B(_128_),
    .Y(_178_)
  );
  sky130_fd_sc_hd__nor3_1 _259_ (
    .A(_132_),
    .B(_133_),
    .C(_164_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__o21a_1 _260_ (
    .A1(_133_),
    .A2(_164_),
    .B1(_132_),
    .X(_130_)
  );
  sky130_fd_sc_hd__nor2_1 _261_ (
    .A(_129_),
    .B(_130_),
    .Y(_179_)
  );
  sky130_fd_sc_hd__xnor2_1 _262_ (
    .A(_089_),
    .B(_105_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__xnor2_1 _263_ (
    .A(_166_),
    .B(_131_),
    .Y(_180_)
  );
  assign _089_ = a[15];
  assign _105_ = b[15];
  assign _088_ = a[14];
  assign _104_ = b[14];
  assign _087_ = a[13];
  assign _103_ = b[13];
  assign _086_ = a[12];
  assign _102_ = b[12];
  assign _085_ = a[11];
  assign _101_ = b[11];
  assign _084_ = a[10];
  assign _100_ = b[10];
  assign _098_ = a[9];
  assign _114_ = b[9];
  assign _097_ = a[8];
  assign _113_ = b[8];
  assign _096_ = a[7];
  assign _112_ = b[7];
  assign _095_ = a[6];
  assign _111_ = b[6];
  assign _094_ = a[5];
  assign _110_ = b[5];
  assign _093_ = a[4];
  assign _109_ = b[4];
  assign _092_ = a[3];
  assign _108_ = b[3];
  assign _091_ = a[2];
  assign _107_ = b[2];
  assign _090_ = a[1];
  assign _106_ = b[1];
  assign _083_ = a[0];
  assign _099_ = b[0];
  assign _115_ = cin;
  assign cout = _116_;
  assign s[0] = _174_;
  assign s[1] = _181_;
  assign s[2] = _182_;
  assign s[3] = _183_;
  assign s[4] = _184_;
  assign s[5] = _185_;
  assign s[6] = _186_;
  assign s[7] = _187_;
  assign s[8] = _188_;
  assign s[9] = _189_;
  assign s[10] = _175_;
  assign s[11] = _176_;
  assign s[12] = _177_;
  assign s[13] = _178_;
  assign s[14] = _179_;
  assign s[15] = _180_;
endmodule
