"""physflow: RTL -> GDS through the open physical flow, one driver, one manifest.

Where this sits: synth_search.py searches *synthesis* scripts and proves each
candidate equivalent to the original. This driver takes a netlist that already
passed that gate and carries it the rest of the way to silicon layout --
floorplan, placement, clock tree, routing, stream-out, signoff DRC.

The discipline is carried over rather than loosened:

  * every stage declares its outputs; a stage that does not produce them fails
  * every artifact is sha256-ed into the manifest, so 'better' is checkable
  * the router's own 'number of violations' is NOT the result. detailed_route
    reporting 0 means the router is happy with what it built, not that the
    layout is manufacturable -- those are different claims and magic's signoff
    deck is what tests the second one. Both numbers are recorded, separately.

Toolchain is fixed and measured on this host (WSL Ubuntu-22.04, ~/eda-env):
    yosys 0.9 (apt)      -> liberty-mapped gate netlist, sky130_fd_sc_hd cells
    OpenROAD f12e2f47    -> DEF  (this version has no min-area repair; see below)
    magic 8.3.465        -> GDSII, and signoff DRC with the PDK's own rules
    open_pdks sky130A    -> 2.7 GB under ~/eda-env/share/pdk

Two facts that cost real time and are recorded here so the driver is not
re-debugged every run:
  1. the technology LEF is techlef/sky130_fd_sc_hd__nom.tlef -- the corner
     suffix is part of the name, and the LEF under lef/ has MACROs but zero
     LAYER statements, so reading it alone yields a design that reads, links
     and floorplans and then cannot route.
  2. make_tracks must come after read_liberty (it takes microns and refuses
     with 'units uninitialized' otherwise) AND after initialize_floorplan
     (tracks are laid over the current die). Wrong order creates zero tracks
     and surfaces two stages later in place_pins.
"""
from __future__ import annotations
import hashlib, json, os, subprocess, sys, time

WSL = ["wsl", "-d", "Ubuntu-22.04", "-e", "bash", "-lc"]
PRELUDE = "export LANG=C LC_ALL=C; "
PDK_ROOT = "/root/eda-env/share/pdk"
PDK = PDK_ROOT + "/sky130A"
LIB = PDK + "/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib"
TLEF = PDK + "/libs.ref/sky130_fd_sc_hd/techlef/sky130_fd_sc_hd__nom.tlef"
CLEF = PDK + "/libs.ref/sky130_fd_sc_hd/lef/sky130_fd_sc_hd.lef"
CGDS = PDK + "/libs.ref/sky130_fd_sc_hd/gds/sky130_fd_sc_hd.gds"
MAGICRC = PDK + "/libs.tech/magic/sky130A.magicrc"


def sh(cmd: str, t: int = 540) -> tuple:
    r = subprocess.run(WSL + [PRELUDE + cmd], capture_output=True, text=True, timeout=t,
                       encoding="utf-8", errors="replace")
    return r.returncode, (r.stdout or ""), (r.stderr or "")


def wsl(p: str) -> str:
    p = os.path.abspath(p)
    return "/mnt/" + p[0].lower() + p[2:].replace("\\", "/")


def sha256(p: str) -> str:
    h = hashlib.sha256()
    with open(p, "rb") as f:
        for b in iter(lambda: f.read(1 << 20), b""):
            h.update(b)
    return h.hexdigest()


def clk_port(rtl: str) -> str:
    """Return the clock port name, or '' for a purely combinational design.

    Load-bearing: calling create_clock or clock_tree_synthesis on a design with
    no clock does not fail cleanly, so the driver has to know the shape first.
    """
    import re
    txt = open(rtl, encoding="utf-8", errors="replace").read()
    m = re.search(r"module\s+\w+\s*\(([^)]*)\)", txt)
    if not m:
        return ""
    for port in m.group(1).split(","):
        nm = port.strip().split()[-1] if port.strip() else ""
        if nm in ("clk", "clock", "CLK", "CLOCK"):
            return nm
    return ""


SYN_YS = """read_verilog {rtl}
synth -top {top} -flatten
dfflibmap -liberty {lib}
abc -liberty {lib} -constr /dev/null
setundef -zero
write_verilog -noattr {netlist}
stat
"""

OR_TCL = """# generated by physflow.py -- do not hand-edit; the order of stages is the content
set PDK   "%(pdk)s"
set DESIGN "%(design)s"
set OUT   $::env(OUTDIR)
set LIB   "%(lib)s"
set TLEF  "%(tlef)s"
set CLEF  "%(clef)s"

proc stage {n} { puts "STAGE_BEGIN $n"; flush stdout }
proc ok {n}    { puts "STAGE_OK $n";    flush stdout }

stage read
read_lef $TLEF
read_lef $CLEF
read_liberty $LIB
read_verilog $::env(NETLIST)
link_design $DESIGN
ok read

stage sanitize
# A constant in the RTL comes through yosys as a net, and OpenROAD's Verilog
# reader labels that net GROUND by name. TritonRoute then refuses to route it --
# "[ERROR DRT-0305] Net zero_ of signal type GROUND is not routable, move to
# special nets" -- which is a routing failure with nothing wrong in the layout.
# The fix is to keep POWER/GROUND only on the PDK's real power nets and demote
# everything else back to SIGNAL. arbiter16 (one 1'b1 in the source) hits this;
# every design without a constant does not, which is why it looks random.
set pwr {VPWR VGND VSUBS VPB VNB}
set blk [ord::get_db_block]
set nfix 0
foreach net [$blk getNets] {
  set st [$net getSigType]
  if {$st eq "GROUND" || $st eq "POWER"} {
    if {[lsearch -exact $pwr [$net getName]] < 0} {
      $net setSigType SIGNAL
      incr nfix
    }
  }
}
puts "SANITIZED_NETS $nfix"
ok sanitize

stage floorplan
initialize_floorplan -utilization %(util)s -aspect_ratio 1.0 -core_space 5 -site unithd
ok floorplan

stage tracks
make_tracks li1  -x_offset 0.23 -x_pitch 0.46 -y_offset 0.17 -y_pitch 0.34
make_tracks met1 -x_offset 0.17 -x_pitch 0.34 -y_offset 0.17 -y_pitch 0.34
make_tracks met2 -x_offset 0.23 -x_pitch 0.46 -y_offset 0.23 -y_pitch 0.46
make_tracks met3 -x_offset 0.34 -x_pitch 0.68 -y_offset 0.34 -y_pitch 0.68
make_tracks met4 -x_offset 0.46 -x_pitch 0.92 -y_offset 0.46 -y_pitch 0.92
make_tracks met5 -x_offset 1.70 -x_pitch 3.40 -y_offset 1.70 -y_pitch 3.40
ok tracks

stage pin_place
place_pins -random -hor_layers met3 -ver_layers met2
ok pin_place

stage global_place
global_placement -density 0.6
ok global_place

stage detailed_place
detailed_placement
check_placement
ok detailed_place

%(cts)s

stage filler
filler_placement "sky130_fd_sc_hd__fill_1 sky130_fd_sc_hd__fill_2 sky130_fd_sc_hd__fill_4"
ok filler

stage route
global_route
detailed_route -output_drc "$OUT/drc.rpt"
ok route

stage write
write_def "$OUT/$DESIGN.def"
write_verilog "$OUT/${DESIGN}_routed.v"
report_design_area
ok write
puts "FLOW_DONE"
"""

CTS_BLOCK = """stage cts
create_clock -name clk -period %(period)s [get_ports %(clk)s]
clock_tree_synthesis -buf_list sky130_fd_sc_hd__clkbuf_4 -root_buf sky130_fd_sc_hd__clkbuf_4
set_propagated_clock [all_clocks]
# CTS inserts buffers that it does not legalise itself. Without this second
# placement pass the router reports 'Found pin outside die area in instance
# clkbuf_*', naming a cell CTS made one stage earlier.
detailed_placement
ok cts"""

NO_CLK_BLOCK = """# No clock port: nothing to build a tree for. Recorded rather than skipped
# silently, because 'no CTS stage' and 'CTS that did nothing' are different
# facts about a run.
stage cts
puts "NO_CLOCK_PORT -- combinational design, clock tree not applicable"
ok cts"""

DEF2GDS_TCL = """# generated by physflow.py
drc off
crashbackups stop
set PDK "%(pdk)s"
set DEF $::env(DEF)
set OUT $::env(GDSOUT)
gds readonly true
gds rescale false
gds read %(cgds)s
puts "GDS_LIB_READ"
def read $DEF
puts "DEF_READ"
load %(design)s -dereference
select top cell
gds write $OUT
puts "GDS_WRITTEN"
quit -noprompt
"""

DRC_TCL = """# generated by physflow.py -- signoff DRC, not the router's own check
drc off
gds readonly true
gds rescale false
gds read %(design)s.gds
load %(design)s
select top cell
drc check
drc catchup
puts "DRC_TOTAL [drc list count]"
foreach v [drc listall why] { puts "VIOL $v" }
quit -noprompt
"""


def run_design(rtl: str, design: str, outroot: str, util: int = 30, period: float = 10.0) -> dict:
    d = os.path.join(outroot, design)
    os.makedirs(d, exist_ok=True)
    netlist = os.path.join(d, design + "_syn.v")
    tcl_or = os.path.join(d, "phys.tcl")
    tcl_gds = os.path.join(d, "def2gds.tcl")
    tcl_drc = os.path.join(d, "drc.tcl")
    logd = os.path.join(d, "logs")
    os.makedirs(logd, exist_ok=True)

    rec = {"design": design, "rtl": rtl, "utilization": util, "clock_period": period,
           "stages": {}, "artifacts": {}, "ok": False}

    # --- stage synth (yosys, sky130 liberty) ---------------------------------
    ys = os.path.join(d, "syn.ys")
    open(ys, "w", encoding="utf-8", newline="\n").write(
        SYN_YS.format(rtl=wsl(rtl), top=design, lib=LIB, netlist=wsl(netlist)))
    t0 = time.time()
    rc, so, se = sh("yosys -q -s %s > %s/synth.log 2>&1; echo RC=$?" % (wsl(ys), wsl(logd)), t=540)
    rec["stages"]["synth"] = {"ok": os.path.exists(netlist), "seconds": round(time.time() - t0, 1)}
    if not os.path.exists(netlist):
        rec["error"] = "synth produced no netlist"
        return rec
    rec["artifacts"]["netlist"] = {"path": netlist, "sha256": sha256(netlist),
                                   "bytes": os.path.getsize(netlist)}
    cells = sh("grep -o 'sky130_fd_sc_hd__[a-z0-9_]*' %s | sort -u | wc -l" % wsl(netlist))[1].strip()
    rec["mapped_cell_types"] = int(cells or 0)

    # --- stage physical (OpenROAD) ------------------------------------------
    ck = clk_port(rtl)
    cts = (CTS_BLOCK % {"period": period, "clk": ck}) if ck else NO_CLK_BLOCK
    open(tcl_or, "w", encoding="utf-8", newline="\n").write(
        OR_TCL % {"pdk": PDK, "design": design, "lib": LIB, "tlef": TLEF,
                  "clef": CLEF, "util": util, "cts": cts})
    t0 = time.time()
    sh("mkdir -p %s; cd %s; export PATH=/root/eda-env/bin:$PATH PDK=%s PDK_ROOT=%s "
       "DESIGN=%s NETLIST=%s OUTDIR=%s; "
       "timeout 520 openroad -no_init -exit %s > %s/openroad.log 2>&1; echo RC=$?"
       % (wsl(d), wsl(d), PDK, PDK_ROOT, design, wsl(netlist), wsl(d), wsl(tcl_or), wsl(logd)), t=560)
    ol = open(os.path.join(logd, "openroad.log"), encoding="utf-8", errors="replace").read()
    rec["stages"]["physical"] = {
        "ok": "FLOW_DONE" in ol, "seconds": round(time.time() - t0, 1),
        "stage_ok": [l.split()[1] for l in ol.splitlines() if l.startswith("STAGE_OK")],
        "error": next((l for l in ol.splitlines() if l.startswith(("Error", "[ERROR"))), ""),
        "route_violations": (lambda m: int(m.group(1)) if m else None)(
            __import__("re").search(r"Number of violations = (\d+)", ol[::-1].replace("\n", " ", 1)[::-1])),
    }
    for role, fn in (("def", design + ".def"), ("routed_verilog", design + "_routed.v")):
        p = os.path.join(d, fn)
        if os.path.exists(p):
            rec["artifacts"][role] = {"path": p, "sha256": sha256(p), "bytes": os.path.getsize(p)}
    m = __import__("re").search(r"Design area ([\d.]+) u\^2\s+([\d.]+)% utilization", ol)
    if m:
        rec["design_area_um2"] = float(m.group(1))
        rec["utilization_pct"] = float(m.group(2))
    if not rec["stages"]["physical"]["ok"]:
        return rec

    # --- stage gds (magic) ---------------------------------------------------
    open(tcl_gds, "w", encoding="utf-8", newline="\n").write(
        DEF2GDS_TCL % {"pdk": PDK, "cgds": CGDS, "design": design})
    gds = os.path.join(d, design + ".gds")
    t0 = time.time()
    sh("cd %s; export PATH=/root/eda-env/bin:$PATH PDK=%s PDK_ROOT=%s DEF=%s GDSOUT=%s; "
       "timeout 300 magic -dnull -noconsole -rcfile %s %s > %s/magic.log 2>&1; echo RC=$?"
       % (wsl(d), PDK, PDK_ROOT, wsl(os.path.join(d, design + ".def")), wsl(gds),
          MAGICRC, wsl(tcl_gds), wsl(logd)), t=380)
    ml = open(os.path.join(logd, "magic.log"), encoding="utf-8", errors="replace").read()
    rec["stages"]["gds"] = {"ok": os.path.exists(gds), "seconds": round(time.time() - t0, 1),
                            "wrote": "GDS_WRITTEN" in ml}
    if not os.path.exists(gds):
        return rec
    rec["artifacts"]["gds"] = {"path": gds, "sha256": sha256(gds), "bytes": os.path.getsize(gds)}

    # --- stage signoff DRC (magic's deck, by design and by name) -------------
    open(tcl_drc, "w", encoding="utf-8", newline="\n").write(DRC_TCL % {"design": design})
    t0 = time.time()
    sh("cd %s; export PATH=/root/eda-env/bin:$PATH PDK=%s PDK_ROOT=%s; "
       "timeout 400 magic -dnull -noconsole -rcfile %s %s > %s/drc.log 2>&1; echo RC=$?"
       % (wsl(d), PDK, PDK_ROOT, MAGICRC, wsl(tcl_drc), wsl(logd)), t=480)
    dl = open(os.path.join(logd, "drc.log"), encoding="utf-8", errors="replace").read()
    tot = __import__("re").search(r"DRC_TOTAL \{(\S+) (\d+)\}", dl)
    rec["stages"]["drc"] = {
        "ok": bool(tot), "seconds": round(time.time() - t0, 1),
        "violations": int(tot.group(2)) if tot else None,
        "rules": sorted({l[len("VIOL "):].split(" (")[0].strip()
                         for l in dl.splitlines() if l.startswith("VIOL ") and not l.startswith("VIOL {")}),
    }
    rec["ok"] = all(s.get("ok") for s in rec["stages"].values())
    rec["manifest"] = hashlib.sha256(
        ("|".join(sorted(a["sha256"] for a in rec["artifacts"].values()))).encode()).hexdigest()
    return rec


if __name__ == "__main__":
    root = sys.argv[1] if len(sys.argv) > 1 else r"D:\eda\phys"
    src_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "bench", "src")
    want = sys.argv[2].split(",") if len(sys.argv) > 2 else None
    rtl_files = sorted(f[:-2] for f in os.listdir(src_dir) if f.endswith(".v"))
    if want:
        rtl_files = [d for d in rtl_files if d in want]
    out = []
    for design in rtl_files:
        rtl = os.path.join(src_dir, design + ".v")
        rec = run_design(rtl, design, root)
        out.append(rec)
        print(json.dumps({k: rec.get(k) for k in
                          ("design", "ok", "mapped_cell_types", "design_area_um2",
                           "utilization_pct")}, ensure_ascii=False), flush=True)
        print("   stages:", {k: v.get("ok") for k, v in rec["stages"].items()},
              "| drc:", rec["stages"].get("drc", {}).get("violations"), flush=True)
    os.makedirs(root, exist_ok=True)
    res = os.path.join(root, "results.json")
    prev = json.load(open(res, encoding="utf-8")) if os.path.exists(res) else {}
    for r in out:
        prev[r["design"]] = r
    json.dump(prev, open(res, "w", encoding="utf-8"), indent=1, ensure_ascii=False)
    print("\nwrote", res)
