/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module arbiter16(req, gnt);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  output [15:0] gnt;
  wire [15:0] m;
  input [15:0] req;
  sky130_fd_sc_hd__and2_0 _096_ (
    .A(_087_),
    .B(_080_),
    .X(_053_)
  );
  sky130_fd_sc_hd__o21ai_0 _097_ (
    .A1(_087_),
    .A2(_080_),
    .B1(_088_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__nor2_1 _098_ (
    .A(_053_),
    .B(_062_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__or3_1 _099_ (
    .A(_087_),
    .B(_080_),
    .C(_088_),
    .X(_063_)
  );
  sky130_fd_sc_hd__and3_1 _100_ (
    .A(_089_),
    .B(_062_),
    .C(_063_),
    .X(_055_)
  );
  sky130_fd_sc_hd__or4_4 _101_ (
    .A(_087_),
    .B(_080_),
    .C(_088_),
    .D(_089_),
    .X(_064_)
  );
  sky130_fd_sc_hd__nand2_1 _102_ (
    .A(_090_),
    .B(_064_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__a21oi_1 _103_ (
    .A1(_089_),
    .A2(_063_),
    .B1(_065_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__or2_2 _104_ (
    .A(_090_),
    .B(_064_),
    .X(_066_)
  );
  sky130_fd_sc_hd__and3_1 _105_ (
    .A(_091_),
    .B(_065_),
    .C(_066_),
    .X(_057_)
  );
  sky130_fd_sc_hd__o21ai_0 _106_ (
    .A1(_091_),
    .A2(_066_),
    .B1(_092_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__a21oi_1 _107_ (
    .A1(_091_),
    .A2(_066_),
    .B1(_067_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__nor4_4 _108_ (
    .A(_090_),
    .B(_091_),
    .C(_092_),
    .D(_064_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nand2b_1 _109_ (
    .A_N(_068_),
    .B(_093_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _110_ (
    .A(_067_),
    .SLEEP(_069_),
    .X(_059_)
  );
  sky130_fd_sc_hd__or2b_1 _111_ (
    .A(_093_),
    .B_N(_068_),
    .X(_070_)
  );
  sky130_fd_sc_hd__and3_1 _112_ (
    .A(_094_),
    .B(_069_),
    .C(_070_),
    .X(_060_)
  );
  sky130_fd_sc_hd__or2_2 _113_ (
    .A(_094_),
    .B(_070_),
    .X(_071_)
  );
  sky130_fd_sc_hd__nand2_1 _114_ (
    .A(_095_),
    .B(_071_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__a21oi_1 _115_ (
    .A1(_094_),
    .A2(_070_),
    .B1(_072_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__or4b_1 _116_ (
    .A(_093_),
    .B(_094_),
    .C(_095_),
    .D_N(_068_),
    .X(_073_)
  );
  sky130_fd_sc_hd__nand2_1 _117_ (
    .A(_081_),
    .B(_073_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__a21oi_1 _118_ (
    .A1(_095_),
    .A2(_071_),
    .B1(_074_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__or2_2 _119_ (
    .A(_081_),
    .B(_073_),
    .X(_075_)
  );
  sky130_fd_sc_hd__and3_1 _120_ (
    .A(_082_),
    .B(_074_),
    .C(_075_),
    .X(_048_)
  );
  sky130_fd_sc_hd__o21ai_0 _121_ (
    .A1(_082_),
    .A2(_075_),
    .B1(_083_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__a21oi_1 _122_ (
    .A1(_082_),
    .A2(_075_),
    .B1(_076_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__or4_4 _123_ (
    .A(_081_),
    .B(_082_),
    .C(_083_),
    .D(_073_),
    .X(_077_)
  );
  sky130_fd_sc_hd__and3_1 _124_ (
    .A(_084_),
    .B(_076_),
    .C(_077_),
    .X(_050_)
  );
  sky130_fd_sc_hd__o21ai_0 _125_ (
    .A1(_084_),
    .A2(_077_),
    .B1(_085_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__a21oi_1 _126_ (
    .A1(_084_),
    .A2(_077_),
    .B1(_078_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__or3_1 _127_ (
    .A(_084_),
    .B(_085_),
    .C(_077_),
    .X(_079_)
  );
  sky130_fd_sc_hd__and3_1 _128_ (
    .A(_086_),
    .B(_078_),
    .C(_079_),
    .X(_052_)
  );
  assign gnt[0] = 1'h0;
  assign m = { gnt[15:1], 1'h0 };
  assign _087_ = req[1];
  assign _080_ = req[0];
  assign gnt[1] = _053_;
  assign _088_ = req[2];
  assign gnt[2] = _054_;
  assign _089_ = req[3];
  assign gnt[3] = _055_;
  assign _090_ = req[4];
  assign gnt[4] = _056_;
  assign _091_ = req[5];
  assign gnt[5] = _057_;
  assign _092_ = req[6];
  assign gnt[6] = _058_;
  assign _093_ = req[7];
  assign gnt[7] = _059_;
  assign _094_ = req[8];
  assign gnt[8] = _060_;
  assign _095_ = req[9];
  assign gnt[9] = _061_;
  assign _081_ = req[10];
  assign gnt[10] = _047_;
  assign _082_ = req[11];
  assign gnt[11] = _048_;
  assign _083_ = req[12];
  assign gnt[12] = _049_;
  assign _084_ = req[13];
  assign gnt[13] = _050_;
  assign _085_ = req[14];
  assign gnt[14] = _051_;
  assign _086_ = req[15];
  assign gnt[15] = _052_;
endmodule
