/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module prio32(x, y, v);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  output v;
  input [31:0] x;
  output [31:0] y;
  sky130_fd_sc_hd__or4_4 _142_ (
    .A(_101_),
    .B(_104_),
    .C(_079_),
    .D(_090_),
    .X(_061_)
  );
  sky130_fd_sc_hd__nor4_4 _143_ (
    .A(_107_),
    .B(_105_),
    .C(_106_),
    .D(_061_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__or4b_4 _144_ (
    .A(_109_),
    .B(_110_),
    .C(_108_),
    .D_N(_062_),
    .X(_063_)
  );
  sky130_fd_sc_hd__nor4_4 _145_ (
    .A(_082_),
    .B(_080_),
    .C(_081_),
    .D(_063_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__nor2_1 _146_ (
    .A(_084_),
    .B(_085_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__nor2_1 _147_ (
    .A(_086_),
    .B(_087_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__nand4b_2 _148_ (
    .A_N(_083_),
    .B(_064_),
    .C(_065_),
    .D(_066_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nor2_1 _149_ (
    .A(_088_),
    .B(_089_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nor2_1 _150_ (
    .A(_091_),
    .B(_092_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nor2_1 _151_ (
    .A(_093_),
    .B(_094_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__nand4b_4 _152_ (
    .A_N(_067_),
    .B(_068_),
    .C(_069_),
    .D(_070_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__nor2_1 _153_ (
    .A(_095_),
    .B(_096_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__or4b_4 _154_ (
    .A(_097_),
    .B(_098_),
    .C(_071_),
    .D_N(_072_),
    .X(_073_)
  );
  sky130_fd_sc_hd__or2_2 _155_ (
    .A(_099_),
    .B(_100_),
    .X(_074_)
  );
  sky130_fd_sc_hd__or4_1 _156_ (
    .A(_102_),
    .B(_103_),
    .C(_073_),
    .D(_074_),
    .X(_078_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _157_ (
    .A(_090_),
    .SLEEP(_079_),
    .X(_121_)
  );
  sky130_fd_sc_hd__nor3b_1 _158_ (
    .A(_079_),
    .B(_090_),
    .C_N(_101_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__nor4b_1 _159_ (
    .A(_101_),
    .B(_079_),
    .C(_090_),
    .D_N(_104_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__lpflow_inputiso0p_1 _160_ (
    .A(_105_),
    .SLEEP(_061_),
    .X(_136_)
  );
  sky130_fd_sc_hd__nor3b_1 _161_ (
    .A(_061_),
    .B(_105_),
    .C_N(_106_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__nor4b_1 _162_ (
    .A(_105_),
    .B(_106_),
    .C(_061_),
    .D_N(_107_),
    .Y(_138_)
  );
  sky130_fd_sc_hd__and2_0 _163_ (
    .A(_108_),
    .B(_062_),
    .X(_139_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1n_1 _164_ (
    .A(_108_),
    .SLEEP_B(_062_),
    .X(_075_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _165_ (
    .A(_109_),
    .SLEEP(_075_),
    .X(_140_)
  );
  sky130_fd_sc_hd__nor3b_1 _166_ (
    .A(_075_),
    .B(_109_),
    .C_N(_110_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__lpflow_inputiso0p_1 _167_ (
    .A(_080_),
    .SLEEP(_063_),
    .X(_111_)
  );
  sky130_fd_sc_hd__nor3b_1 _168_ (
    .A(_063_),
    .B(_080_),
    .C_N(_081_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__nor4b_1 _169_ (
    .A(_080_),
    .B(_081_),
    .C(_063_),
    .D_N(_082_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__lpflow_inputiso0n_1 _170_ (
    .A(_083_),
    .SLEEP_B(_064_),
    .X(_114_)
  );
  sky130_fd_sc_hd__or2b_1 _171_ (
    .A(_083_),
    .B_N(_064_),
    .X(_076_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _172_ (
    .A(_084_),
    .SLEEP(_076_),
    .X(_115_)
  );
  sky130_fd_sc_hd__nor3b_1 _173_ (
    .A(_076_),
    .B(_084_),
    .C_N(_085_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__nand2b_1 _174_ (
    .A_N(_076_),
    .B(_065_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _175_ (
    .A(_086_),
    .SLEEP(_077_),
    .X(_117_)
  );
  sky130_fd_sc_hd__nor3b_1 _176_ (
    .A(_077_),
    .B(_086_),
    .C_N(_087_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__lpflow_inputiso0p_1 _177_ (
    .A(_088_),
    .SLEEP(_067_),
    .X(_119_)
  );
  sky130_fd_sc_hd__nor3b_1 _178_ (
    .A(_067_),
    .B(_088_),
    .C_N(_089_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__nand2b_1 _179_ (
    .A_N(_067_),
    .B(_068_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _180_ (
    .A(_091_),
    .SLEEP(_056_),
    .X(_122_)
  );
  sky130_fd_sc_hd__nor3b_1 _181_ (
    .A(_056_),
    .B(_091_),
    .C_N(_092_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__nand2b_1 _182_ (
    .A_N(_056_),
    .B(_069_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _183_ (
    .A(_093_),
    .SLEEP(_057_),
    .X(_124_)
  );
  sky130_fd_sc_hd__nor3b_1 _184_ (
    .A(_057_),
    .B(_093_),
    .C_N(_094_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__lpflow_inputiso0p_1 _185_ (
    .A(_095_),
    .SLEEP(_071_),
    .X(_126_)
  );
  sky130_fd_sc_hd__nor3b_1 _186_ (
    .A(_071_),
    .B(_095_),
    .C_N(_096_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__nand2b_1 _187_ (
    .A_N(_071_),
    .B(_072_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _188_ (
    .A(_097_),
    .SLEEP(_058_),
    .X(_128_)
  );
  sky130_fd_sc_hd__nor3b_1 _189_ (
    .A(_058_),
    .B(_097_),
    .C_N(_098_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__lpflow_inputiso0p_1 _190_ (
    .A(_099_),
    .SLEEP(_073_),
    .X(_130_)
  );
  sky130_fd_sc_hd__nor3b_1 _191_ (
    .A(_073_),
    .B(_099_),
    .C_N(_100_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__inv_1 _192_ (
    .A(_102_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__nor3_1 _193_ (
    .A(_059_),
    .B(_073_),
    .C(_074_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__inv_1 _194_ (
    .A(_103_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__nor4_1 _195_ (
    .A(_102_),
    .B(_060_),
    .C(_073_),
    .D(_074_),
    .Y(_134_)
  );
  assign y[0] = x[0];
  assign _102_ = x[30];
  assign _103_ = x[31];
  assign _099_ = x[28];
  assign _100_ = x[29];
  assign _097_ = x[26];
  assign _098_ = x[27];
  assign _095_ = x[24];
  assign _096_ = x[25];
  assign _093_ = x[22];
  assign _094_ = x[23];
  assign _091_ = x[20];
  assign _092_ = x[21];
  assign _088_ = x[18];
  assign _089_ = x[19];
  assign _086_ = x[16];
  assign _087_ = x[17];
  assign _084_ = x[14];
  assign _085_ = x[15];
  assign _082_ = x[12];
  assign _083_ = x[13];
  assign _080_ = x[10];
  assign _081_ = x[11];
  assign _109_ = x[8];
  assign _110_ = x[9];
  assign _107_ = x[6];
  assign _108_ = x[7];
  assign _105_ = x[4];
  assign _106_ = x[5];
  assign _101_ = x[2];
  assign _104_ = x[3];
  assign _079_ = x[0];
  assign _090_ = x[1];
  assign v = _078_;
  assign y[1] = _121_;
  assign y[2] = _132_;
  assign y[3] = _135_;
  assign y[4] = _136_;
  assign y[5] = _137_;
  assign y[6] = _138_;
  assign y[7] = _139_;
  assign y[8] = _140_;
  assign y[9] = _141_;
  assign y[10] = _111_;
  assign y[11] = _112_;
  assign y[12] = _113_;
  assign y[13] = _114_;
  assign y[14] = _115_;
  assign y[15] = _116_;
  assign y[16] = _117_;
  assign y[17] = _118_;
  assign y[18] = _119_;
  assign y[19] = _120_;
  assign y[20] = _122_;
  assign y[21] = _123_;
  assign y[22] = _124_;
  assign y[23] = _125_;
  assign y[24] = _126_;
  assign y[25] = _127_;
  assign y[26] = _128_;
  assign y[27] = _129_;
  assign y[28] = _130_;
  assign y[29] = _131_;
  assign y[30] = _133_;
  assign y[31] = _134_;
endmodule
