/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module adder8(a, b, cin, s, cout);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  input [7:0] a;
  input [7:0] b;
  input cin;
  output cout;
  output [7:0] s;
  sky130_fd_sc_hd__maj3_2 _077_ (
    .A(_036_),
    .B(_044_),
    .C(_052_),
    .X(_054_)
  );
  sky130_fd_sc_hd__maj3_2 _078_ (
    .A(_037_),
    .B(_045_),
    .C(_054_),
    .X(_055_)
  );
  sky130_fd_sc_hd__maj3_2 _079_ (
    .A(_038_),
    .B(_046_),
    .C(_055_),
    .X(_056_)
  );
  sky130_fd_sc_hd__maj3_2 _080_ (
    .A(_039_),
    .B(_047_),
    .C(_056_),
    .X(_057_)
  );
  sky130_fd_sc_hd__maj3_2 _081_ (
    .A(_040_),
    .B(_048_),
    .C(_057_),
    .X(_058_)
  );
  sky130_fd_sc_hd__maj3_2 _082_ (
    .A(_041_),
    .B(_049_),
    .C(_058_),
    .X(_059_)
  );
  sky130_fd_sc_hd__maj3_2 _083_ (
    .A(_042_),
    .B(_050_),
    .C(_059_),
    .X(_060_)
  );
  sky130_fd_sc_hd__maj3_1 _084_ (
    .A(_043_),
    .B(_051_),
    .C(_060_),
    .X(_053_)
  );
  sky130_fd_sc_hd__xnor2_1 _085_ (
    .A(_036_),
    .B(_044_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__xnor2_1 _086_ (
    .A(_052_),
    .B(_061_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__xnor2_1 _087_ (
    .A(_037_),
    .B(_045_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__xnor2_1 _088_ (
    .A(_054_),
    .B(_062_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__xnor2_1 _089_ (
    .A(_038_),
    .B(_046_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__xnor2_1 _090_ (
    .A(_055_),
    .B(_063_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__xnor2_1 _091_ (
    .A(_039_),
    .B(_047_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__xnor2_1 _092_ (
    .A(_056_),
    .B(_064_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__xnor2_1 _093_ (
    .A(_040_),
    .B(_048_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__xnor2_1 _094_ (
    .A(_057_),
    .B(_065_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__xnor2_1 _095_ (
    .A(_041_),
    .B(_049_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__xnor2_1 _096_ (
    .A(_058_),
    .B(_066_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__xnor2_1 _097_ (
    .A(_042_),
    .B(_050_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__xnor2_1 _098_ (
    .A(_067_),
    .B(_059_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__xnor2_1 _099_ (
    .A(_043_),
    .B(_051_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__xnor2_1 _100_ (
    .A(_060_),
    .B(_068_),
    .Y(_076_)
  );
  assign _043_ = a[7];
  assign _051_ = b[7];
  assign _042_ = a[6];
  assign _050_ = b[6];
  assign _041_ = a[5];
  assign _049_ = b[5];
  assign _040_ = a[4];
  assign _048_ = b[4];
  assign _039_ = a[3];
  assign _047_ = b[3];
  assign _038_ = a[2];
  assign _046_ = b[2];
  assign _037_ = a[1];
  assign _045_ = b[1];
  assign _036_ = a[0];
  assign _044_ = b[0];
  assign _052_ = cin;
  assign cout = _053_;
  assign s[0] = _069_;
  assign s[1] = _070_;
  assign s[2] = _071_;
  assign s[3] = _072_;
  assign s[4] = _073_;
  assign s[5] = _074_;
  assign s[6] = _075_;
  assign s[7] = _076_;
endmodule
